void setClippingRectangle(void);
void DrawCircle(float, float, float, int);
void DrawBoundingCircle(float, float, float, int, float*);
void drawSquare(void);
void drawUpperArm(void);
void drawLowerArm(void);
void drawBody(void);
void drawHead(void);
void drawEye(void);
void drawSpider(float *);
void lookForCollision(struct spider, struct spider);
